name: Release

on:
  push:
    tags:
      - 'v*'  # 触发条件：当推送标签以 v 开头时
  workflow_dispatch:  # 允许手动触发
    inputs:
      tag_name:
        description: '要验证的标签名称'
        required: true
        default: 'v3.3.5'

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境
    
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: 验证 GitHub 标签是否同步
        shell: bash  # 使用 bash shell (已预装在 GitHub Actions Windows 环境中)
        env:
          TAG_NAME: ${{ github.event.inputs.tag_name || github.ref_name }}
          MSYS_NO_PATHCONV: 1  # 防止 Windows 路径转换问题
        run: |
          # 重试验证标签是否存在
          MAX_ATTEMPTS=5
          DELAY=10

          for ((attempt=1; attempt<=$MAX_ATTEMPTS; attempt++)); do
            echo "尝试验证标签 $TAG_NAME (尝试 $attempt/$MAX_ATTEMPTS)..."
            
            if git ls-remote --tags origin "$TAG_NAME" | grep -q "$TAG_NAME"; then
              echo "标签 $TAG_NAME 已找到"
              break
            fi
            
            if [ $attempt -eq $MAX_ATTEMPTS ]; then
              echo "标签 $TAG_NAME 未在GitHub上找到，达到最大尝试次数"
              exit 1
            fi
            
            echo "标签未找到，等待 $DELAY 秒后重试..."
            sleep $DELAY
          done
          
      - name: 构建和发布
        run: |
          # 示例：构建和发布 .NET 应用
          dotnet build --configuration Release
          dotnet publish -c Release -o publish
